### PR TITLE
Fix npm install executed twice

### LINKED ISSUE #29: npm install -d error: destination path `ng-cordova` already exists
If I run `npm install -d` twice, it will cause an error:

image

### PR DESCRIPTION
**Pull request by giorgiofellipe**
closes #29

### CODE REVIEW

**Comment by felquis** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

File: gulp/tasks/install-source-modules.js [hunk 1]
```diff
@@ -14,14 +14,25 @@ gulp.task('install-source-modules', function() {
       'git clone',
       ionicProject.sourceModules[propertyName],
       path.join('modules', propertyName)
-    )
+    );
+    
+    var cwd = path.join(appRoot.path, 'modules');
+    var modulePath = path.join(cwd, propertyName);
+    var directory = fs.lstatSync(modulePath);
```
Comment (felquis) [inline gulp/tasks/install-source-modules.js]: Interessante, funcionou perfeitamente.
image
